export const EVENT_TYPES = Object.freeze([
  "CONTRACT_VALUE_CONFIRMED", "REVENUE_RECOGNIZED", "RECEIVABLE_CREATED", "CLIENT_PAYMENT_REPORTED", "CLIENT_PAYMENT_CONFIRMED", "RECEIVABLE_REVERSED",
  "COST_INCURRED", "PAYABLE_CREATED", "SUPPLIER_PAYMENT_APPROVED", "SUPPLIER_PAYMENT_CONFIRMED", "COST_REVERSED",
  "EXPENSE_DETECTED", "EXPENSE_ALLOCATED", "EXPENSE_CONFIRMED", "REIMBURSEMENT_APPROVED", "REIMBURSEMENT_PAID", "EXPENSE_REVERSED",
  "PETTY_CASH_ISSUED", "PETTY_CASH_USED", "PETTY_CASH_RETURNED", "PROJECT_ADVANCE_ISSUED", "PROJECT_ADVANCE_SETTLED",
  "PAYROLL_PREPARED", "PAYROLL_APPROVED", "PAYROLL_CONFIRMED", "PAYROLL_PAID", "PAYROLL_REVERSED",
  "CASH_IN", "CASH_OUT", "DIVIDEND", "TAX_PAYMENT", "OTHER_ADJUSTMENT", "REVERSAL", "CORRECTION"
]);
export const EVENT_TYPE_SET = new Set(EVENT_TYPES);
