import { createFinancialEvent, immutableClone } from "./financial-event.mjs";
import {compareCanonicalEventTime} from './canonical-event-time.mjs';
export const DOMAIN_ERRORS=Object.freeze({INVALID_FINANCIAL_HISTORY:"INVALID_FINANCIAL_HISTORY",DUPLICATE_REVERSAL:"DUPLICATE_REVERSAL",DUPLICATE_CORRECTION:"DUPLICATE_CORRECTION",RELATIONSHIP_CYCLE:"RELATIONSHIP_CYCLE",MISSING_RELATIONSHIP_TARGET:"MISSING_RELATIONSHIP_TARGET",INVALID_REVERSAL_TARGET:"INVALID_REVERSAL_TARGET",INVALID_CORRECTION_TARGET:"INVALID_CORRECTION_TARGET",RELATIONSHIP_IDENTITY_MISMATCH:"RELATIONSHIP_IDENTITY_MISMATCH"});
const fail=code=>{const e=new Error(code);e.code=code;throw e};
export function buildCanonicalFinancialHistory(events=[]){const out=events.map(createFinancialEvent),ids=new Set();for(const e of out){if(ids.has(e.eventId))fail(DOMAIN_ERRORS.INVALID_FINANCIAL_HISTORY);ids.add(e.eventId)}return immutableClone(out.sort(compareCanonicalEventTime));}
export function buildFinancialRelationshipGraph(events=[]){const history=buildCanonicalFinancialHistory(events),byEventId=new Map(history.map(e=>[e.eventId,e])),reversalsByOriginalId=new Map(),correctionsByOriginalId=new Map(),edges=new Map();for(const e of history){if(e.reversalOf){if(e.eventType!=="REVERSAL"||e.reversalOf===e.eventId)fail(DOMAIN_ERRORS.INVALID_REVERSAL_TARGET);const o=byEventId.get(e.reversalOf);if(!o)fail(DOMAIN_ERRORS.MISSING_RELATIONSHIP_TARGET);if(o.eventType==="REVERSAL"||o.status!=="confirmed"||e.amount!==o.amount||e.currency!==o.currency||e.companyId!==o.companyId||e.projectId!==o.projectId)fail(DOMAIN_ERRORS.RELATIONSHIP_IDENTITY_MISMATCH);const a=reversalsByOriginalId.get(o.eventId)||[];a.push(e);reversalsByOriginalId.set(o.eventId,a);edges.set(e.eventId,o.eventId)}if(e.correctionOf){if(e.correctionOf===e.eventId||e.eventType==="REVERSAL")fail(DOMAIN_ERRORS.INVALID_CORRECTION_TARGET);const o=byEventId.get(e.correctionOf);if(!o||o.eventType==="REVERSAL"||o.status!=="confirmed"||e.eventType!==o.eventType||e.currency!==o.currency||e.companyId!==o.companyId||e.projectId!==o.projectId)fail(DOMAIN_ERRORS.INVALID_CORRECTION_TARGET);const a=correctionsByOriginalId.get(o.eventId)||[];a.push(e);correctionsByOriginalId.set(o.eventId,a);edges.set(e.eventId,o.eventId)}}for(const v of reversalsByOriginalId.values())if(v.length>1)fail(DOMAIN_ERRORS.DUPLICATE_REVERSAL);for(const v of correctionsByOriginalId.values())if(v.length>1)fail(DOMAIN_ERRORS.DUPLICATE_CORRECTION);const state=new Map(),visit=id=>{if(state.get(id)==="visiting")fail(DOMAIN_ERRORS.RELATIONSHIP_CYCLE);if(state.get(id)==="visited")return;state.set(id,"visiting");if(edges.has(id))visit(edges.get(id));state.set(id,"visited")};for(const id of edges.keys())visit(id);return immutableClone({history,byEventId:[...byEventId],reversalsByOriginalId:[...reversalsByOriginalId],correctionsByOriginalId:[...correctionsByOriginalId]});}
export const relationshipIndex=buildFinancialRelationshipGraph;
export function validateReversalAgainstHistory({reversalEvent,history=[]}={}){try{buildFinancialRelationshipGraph([...history,reversalEvent]);return {ok:true}}catch(error){return {ok:false,error}}}
export function resolveEffectiveFinancialEvents(events=[]){const g=buildFinancialRelationshipGraph(events),rev=new Set(g.reversalsByOriginalId.map(([id])=>id)),corr=new Map(g.correctionsByOriginalId),out=g.history.filter(e=>!e.reversalOf&&!e.correctionOf&&!rev.has(e.eventId));for(const [,cs] of corr)out.push(cs[0]);const ids=new Set(out.map(e=>e.eventId));if(ids.size!==out.length)fail(DOMAIN_ERRORS.INVALID_FINANCIAL_HISTORY);return immutableClone(out.sort(compareCanonicalEventTime));}
