export const COMPARISON_TYPES = Object.freeze({ TYPE_A: "REBUILT_VS_PERSISTED_PROJECTION", TYPE_B: "JOURNAL_WATERMARK_VS_PROJECTION_WATERMARK", TYPE_C: "FINANCIAL_TRUTH_VS_LEGACY", TYPE_D: "MIGRATION_BASELINE_RECONCILIATION" });
export const COMPARISON_STATUS = Object.freeze(["MATCH","MISMATCH","INDETERMINATE","INVALID_INPUT"]);
export const INDETERMINATE_REASONS = Object.freeze(["STALE_REBUILD","INVALID_HISTORY","INSUFFICIENT_EVIDENCE","OBSERVED_STATE_MISSING","UNSUPPORTED_COMPARISON"]);
export const DIFFERENCE_CATEGORIES = Object.freeze(["FINANCIAL_VALUE_DIFFERENCE","WATERMARK_DIFFERENCE","IDENTITY_DIFFERENCE","VERSION_DIFFERENCE","METADATA_DIFFERENCE"]);
export const RECONCILIATION_CONTRACT_VERSION = "1";
